#!/usr/bin/env php
<?php
/**
 * Author: Jason
 */
use App\Foundation\Application;
use App\Providers\AppServiceProvider;
use App\Providers\ConsoleServiceProvider;

/*
 * Register the autoloader and
 * tell it to register the tasks directory
 */
define('ROOT', __DIR__);

/** @var Application $app */
$app = require ROOT.'/bootstrap/app.php';

$app->setFactory('cli');

$app->registerDirs([
    ROOT.'/app/Tasks',
    ROOT.'/app/Jobs',
]);

$app->registerServiceProviders([
    AppServiceProvider::class,
    ConsoleServiceProvider::class,
]);

$app->run($argv);
